### ISSUE TITLE
not building on ubuntu 24_04

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#1292]
with the current matrix of docker images (from `azure-pipelines.yml`):

```
    # Docker Images
    strategy:
      matrix:
        ubuntu_20_04:
          image: 'tfcollins/libiio_ubuntu_20_04-ci:latest'
          artifactName: 'Linux-Ubuntu-20.04'
        ubuntu_22_04:
          image: 'tfcollins/libiio_ubuntu_22_04-ci:latest'
          artifactName: 'Linux-Ubuntu-22.04'        
        fedora28:
          image: 'tfcollins/libiio_fedora_28-ci:latest'
          artifactName: 'Linux-Fedora-28'
        fedora34:
          image: 'tfcollins/libiio_fedora_34-ci:latest'
          artifactName: 'Linux-Fedora-34'
        debian_bullseye:
          image: 'tfcollins/libiio_debian_bullseye-ci:latest'
          artifactName: 'Linux-Debian-11'
        debian_bookworm:
          image: 'tfcollins/libiio_debian_bookworm-ci:latest'
          artifactName: 'Linux-Debian-12'
        opensuse_15_4:
          image: 'tfcollins/libiio_opensuse_15_4-ci:latest'
          artifactName: 'Linux-openSUSE-15.4'
        centos_7:
          image: 'tfcollins/libiio_centos_7-ci:latest'
          artifactName: 'Linux-CentOS-7'
```

We do cover most of the images that [MathWorks needs](https://www.mathworks.com/support/requirements/matlab-linux.html) but but we are missing : 
 - Ubuntu 24.04 LTS (Noble Numbat) Released : Apr 2024 / EOL : Apr 2029

and we can likely drop centos 7 (unless we have a desire to keep it).
